runners:
  - name: front-vue-runner
    cloud: aws
    instance_type: t3.nano
    machine_image: ami-06fd8a495a537da8b
    preemptible: false
    workflow: .github/workflows/front-vue.yml
    count: 1
