# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: n1hility/cancel-previous-runs@v2
        name: Cancel Previous Runs
        with:
          token: ${{ secrets.PAT }}
      - uses: actions/checkout@v2
        name: Checkout

      - name: Install dependencies
        run: yarn install # this is just for sake of doing it, will use docker

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test:unit
  docker-push:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: n1hility/cancel-previous-runs@v2
        name: Cancel Previous Runs
        with:
          token: ${{ secrets.PAT }}
      - uses: actions/checkout@v2
        name: Checkout

      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          image: sanjibdevnath/front-vue
          tags: $RUNNER_OS.$GITHUB_SHA.$GITHUB_RUN_ID, $RUNNER_OS.$GITHUB_RUN_ID
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
  semgrep-check:
    runs-on: ubuntu-latest
    steps:
      - uses: n1hility/cancel-previous-runs@v2
        name: Cancel Previous Runs
        with:
          token: ${{ secrets.PAT }}

      - uses: actions/checkout@v2
        name: Checkout

      - name: Extract branch name
        id: extract_branch
        run: |
          echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
      - if: ${{ env.BRANCH_NAME == 'master' }}
        uses: returntocorp/semgrep-action@v1
        name: Semgrep
        with:
          publishToken: ${{ secrets.SEMGREP_APP_TOKEN }}
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: [build, docker-push, semgrep-check]
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: n1hility/cancel-previous-runs@v2
        name: Cancel Previous Runs
        with:
          token: ${{ secrets.PAT }}
      - name: Extract branch name
        id: extract_branch
        run: |
          echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
      - if: ${{ env.BRANCH_NAME == 'master' }}
        uses: BetaHuhn/deploy-to-vercel-action@v1
        name: Vercel Deploy Prod
        with:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          GITHUB_TOKEN: ${{ secrets.PAT }}
